export const APP_TOKENS = {
  USER_READ_PORT: Symbol('USER_READ_PORT'),
  CONVERSATION_READ_PORT: Symbol('CONVERSATION_READ_PORT'),
  AGENT_READ_PORT: Symbol('AGENT_READ_PORT'),
  GET_CURRENT_USER_USE_CASE: Symbol('GET_CURRENT_USER_USE_CASE'),
  LIST_USERS_USE_CASE: Symbol('LIST_USERS_USE_CASE'),
  GET_CONVERSATIONS_BY_USER_IDS_USE_CASE: Symbol(
    'GET_CONVERSATIONS_BY_USER_IDS_USE_CASE',
  ),
  GET_AGENTS_BY_CONVERSATION_IDS_USE_CASE: Symbol(
    'GET_AGENTS_BY_CONVERSATION_IDS_USE_CASE',
  ),
} as const;
