// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'src/infra/database/prisma/',
    migrations: {
        path: 'src/infra/database/prisma/migrations',
        seed: 'ts-node src/infra/database/prisma/seeders/seed.ts',
    },
    datasource: {
        url: process.env.DATABASE_URL,
    },
});
